### ISSUE TITLE
Excluded grades

### ISSUE THREAD

**Issue by rrusso** [lsuits/gradereport_forecast#1]
Excluded grades are included in calculation as well as showing up as editable in the UI.

They should be non-inputs, locked, or frozen in the UI and excluded from calculation on grade compute.

Maybe use unset, to unset the grade?

**Comment by chadmazilly** [comment]
This is now fixed. [c9f84c2](https://github.com/lsuits/gradereport_forecast/commit/c9f84c25e47291488582cf90921e6f6aedf122fc)
